
name: GZT Web Deployment Script

on:
  # Triggers the workflow on push or pull request events but for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{js,md}
        commit_message: Prettier Action
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: prettier

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yarn dependencies and build project
        run: |
          yarn install
          yarn build
          yarn export
          # Copy CNAME to build output
          cp CNAME out/

      - name: Deployment
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d out -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}