name: GZT Web Deployment Script

on:
  # Triggers the workflow on push or pull request events but for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use cached node_modules
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Project Dependencies
        run: |
          yarn install

      - name: Build Members JSON and Members IMG
        run: |
          yarn run members-update

      - name: Commit members JSON update
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: CI updates 😎

      - name: Build website
        run: |
          yarn build
          yarn export
          cp CNAME .nojekyll out/

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          prettier_options: --write **/*.{js,md}
          commit_message: Prettier Action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
          clean: false
